#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

apt-get install libaio1

dpkg -i /tmp/in_target.d/oracle-instantclient12.1-basic_12.1.0.2.0-2_amd64.deb
dpkg -i /tmp/in_target.d/oracle-instantclient12.1-sqlplus_12.1.0.2.0-2_amd64.deb
dpkg -i /tmp/in_target.d/oracle-instantclient12.1-devel_12.1.0.2.0-2_amd64.deb

echo "/usr/lib/oracle/12.1/client64/lib/" > /etc/ld.so.conf.d/oracle.conf

export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib/:$LD_LIBRARY_PATH
ldconfig

echo "export ORACLE_HOME=/usr/lib/oracle/12.1/client64" >> /etc/profile.d/oracle.sh
echo "export PATH=\$PATH:\$ORACLE_HOME/bin" >> /etc/profile.d/oracle.sh

export ORACLE_HOME=/usr/lib/oracle/12.1/client64

ln -s /usr/include/oracle/12.1/client64 $ORACLE_HOME/include

pip install cx_Oracle
