#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

cat > "/etc/sysctl.d/10-cassandra-performance.conf" << _EOF_
# See 'http://docs.datastax.com/en/cassandra/2.1/cassandra/install/installRecommendSettings.html'
# for recommended production settings.
vm.max_map_count = 131072

_EOF_

apt-get --allow-unauthenticated install -qy curl
echo "deb http://debian.datastax.com/community stable main" >> /etc/apt/sources.list.d/cassandra.sources.list

apt-get --allow-unauthenticated install -qy wget
wget -q -O - http://debian.datastax.com/debian/repo_key | apt-key add -

#This repo is needed to install 'openjdk-8-jre'
add-apt-repository -y ppa:openjdk-r/ppa

apt-get update
apt-get --allow-unauthenticated install -qy openjdk-7-jdk expect python-dev
apt-get --allow-unauthenticated install -qy libxml2-dev ntp mc
apt-get --allow-unauthenticated install -qy libxslt1-dev python-pexpect
apt-get --allow-unauthenticated install -qy python-migrate build-essential

apt-get --allow-unauthenticated install dsc21=2.1.* cassandra=2.1.* -qy

# The Python Driver 2.0 for Apache Cassandra.
pip2 install cassandra-driver
# Sorted sets support for the Python driver.
pip2 install blist

service cassandra stop
rm -rf /var/lib/cassandra/data/system/*
service cassandra start
