#!/bin/bash

set -e
set -o xtrace

[ -n "${TMP_HOOKS_PATH}" ] || die "Temp hook path not set"

scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/couchbase-enterprise-4.1/couchbase-server-enterprise-4.1.0-centos7.x86_64.rpm $TMP_HOOKS_PATH/.
