#!/bin/bash

source trovestack "source"
[ -z $HOME ] && export HOME="~"
function add_keypair() {
    if [[ -z $(nova --os-username=admin --os-password=$ADMIN_PASSWORD --os-tenant-name=admin --os-auth-url=$TROVE_AUTH_ENDPOINT keypair-list | grep mykey) ]]; then
        exclaim "Adding mykey keypair to nova."
        mkdir -p $HOME/.ssh
        nova --os-username=admin --os-password=$ADMIN_PASSWORD --os-tenant-name=admin --os-auth-url=$TROVE_AUTH_ENDPOINT keypair-add mykey > $HOME/.ssh/mykey
        nova --os-username=admin --os-password=$ADMIN_PASSWORD --os-tenant-name=admin --os-auth-url=$TROVE_AUTH_ENDPOINT keypair-show mykey | grep 'Public key:' | cut -d' ' -f3- > $HOME/.ssh/mykey.pub
        chown -R $USER:$USER $HOME/.ssh
        chmod 700 $HOME/.ssh && chmod 600 $HOME/.ssh/*
        iniset $TROVE_CONF_DIR/trove-taskmanager.conf DEFAULT use_nova_key_name mykey
    fi
}

sleep 3
cmd_stop
sleep 3
add_keypair
iniset $TROVE_CONF DEFAULT max_accepted_volume_size 10
iniset $TROVE_CONF DEFAULT max_instances_per_user 20
sleep 3
cmd_start
sleep 3
